export const optionAttributes = {
  theme: "string",
  layout: "string",
  density: "string",
  "count-format": "string",
  "show-zero-counts": "boolean",
  "show-bookmark-count": "boolean",
  actions: "list",
  "action-mode": "string",
  "repost-count": "string",
  "date-format": "string",
  locale: "string",
  "time-zone": "string",
  "reference-time": "string",
  "show-media": "boolean",
  "show-grok": "boolean",
  "show-menu": "boolean",
  "show-connections": "boolean",
  "media-fit": "string",
  "media-max-height": "number",
  "link-target": "string",
} as const;
export const componentMetadata = [
  {
    name: "thread",
    className: "TwitterThreadElement",
    data: "TwitterThread",
    description: "A list of posts with lines connecting replies.",
    slots: [""],
    parts: ["thread"],
  },
  {
    name: "post",
    className: "TwitterPostElement",
    data: "TwitterPost",
    description: "A post with slots for replacing its parts.",
    slots: [
      "",
      "avatar",
      "header",
      "media",
      "quote",
      "card",
      "actions",
      "footer",
    ],
    parts: ["post", "details"],
  },
  {
    name: "avatar",
    className: "TwitterAvatarElement",
    data: "TwitterAvatar",
    description:
      "A profile image, or the author's initial when no image is set.",
    slots: [],
    parts: ["image"],
  },
  {
    name: "header",
    className: "TwitterHeaderElement",
    data: "TwitterHeader",
    description: "Author, handle, date, and source menu.",
    slots: [],
    parts: ["header", "author", "handle", "date"],
  },
  {
    name: "content",
    className: "TwitterContentElement",
    data: "TwitterContent",
    description: "Post text and links. Text is escaped before rendering.",
    slots: [],
    parts: ["content"],
  },
  {
    name: "media",
    className: "TwitterMediaElement",
    data: "TwitterImage[]",
    description: "One to four images with alt text.",
    slots: [],
    parts: ["media", "image"],
  },
  {
    name: "card",
    className: "TwitterCardElement",
    data: "NonNullable<TwitterPost['card']>",
    description: "A link preview with optional image.",
    slots: [],
    parts: ["image"],
  },
  {
    name: "quote",
    className: "TwitterQuoteElement",
    data: "NonNullable<TwitterPost['quote']>",
    description: "A quoted post.",
    slots: [],
    parts: [],
  },
  {
    name: "actions",
    className: "TwitterActionsElement",
    data: "TwitterPost",
    description:
      "Action buttons and counts. Actions can open links or send events.",
    slots: [],
    parts: [
      "actions",
      "action",
      "count",
      "reply",
      "repost",
      "quote",
      "like",
      "views",
      "bookmark",
      "share",
    ],
  },
] as const;
export function optionKey(attribute: string): string {
  return attribute.replace(/-([a-z])/g, (_, letter: string) =>
    letter.toUpperCase(),
  );
}
